// Code generated by "stringer -type=ErrKind -linecomment=true"; DO NOT EDIT.

package txfile

import "strconv"

const _ErrKind_name = "internal errorcan not create fileconfiguration errorinvalid file sizemeta page invalidinvalid operationpage id out of boundsinvalid parameterout of memorytransaction failed during committransaction failedfinished transactionreadonly transactionunknown error kind"

var _ErrKind_index = [...]uint16{0, 14, 33, 52, 69, 86, 103, 124, 141, 154, 186, 204, 224, 244, 262}

func (i ErrKind) String() string {
	if i < 0 || i >= ErrKind(len(_ErrKind_index)-1) {
		return "ErrKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrKind_name[_ErrKind_index[i]:_ErrKind_index[i+1]]
}
