// Code generated by "stringer -type=ErrKind -linecomment=true"; DO NOT EDIT.

package txfile

import "strconv"

const _ErrKind_name = "configuration errorinvalid parameterinvalid file sizepage id out of boundscan not create filetransaction failedmeta page invalidout of memoryunknown error kind"

var _ErrKind_index = [...]uint8{0, 19, 36, 53, 74, 93, 111, 128, 141, 159}

func (i ErrKind) String() string {
	if i < 0 || i >= ErrKind(len(_ErrKind_index)-1) {
		return "ErrKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrKind_name[_ErrKind_index[i]:_ErrKind_index[i+1]]
}
