# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SETUP_GVM_VERSION: "v0.5.1"

steps:
  - label: ":linux: Testing on {{matrix.platform}}"
    key: linux-test
    command:
      - ".buildkite/scripts/run-go-tests.sh {{matrix.go_version}} {{matrix.platform}}"
    agents:
      provider: "gcp"
      image: "{{matrix.platform}}"
    artifact_paths: "build/*.xml"
    matrix:
      setup:
        go_version:
          - "1.17"
        platform:
          - "family/core-ubuntu-2204"

  - label: ":windows: Testing on Windows"
    key: windows-test
    command: ".buildkite/scripts/run-win-tests.ps1 {{matrix.go_version}}"
    agents:
      provider: "gcp"
      image: "{{matrix.platform}}"
    artifact_paths: "build/*.xml"
    matrix:
      setup:
        go_version:
          - "1.17"
        platform:
          - "family/core-windows-2019"

  - label: ":mac: Testing on MacOS"
    key: macos-test
    command: ".buildkite/scripts/run-go-tests.sh 1.17 generic-13-ventura-x64"
    agents:
      provider: "orka"
      imagePrefix: "generic-13-ventura-x64"
      cpu: 4
    artifact_paths: "build/*.xml"
  - label: ":junit: Junit annotate"
    agents:
      # requires at least "bash", "curl" and "git"
      image: "docker.elastic.co/ci-agent-images/buildkite-junit-annotate:1.0"
    plugins:
      - junit-annotate#v2.7.0:
          artifacts: "build/*.xml"
          fail-build-on-error: true
          run-in-docker: false
    depends_on:
      - step: "linux-test"
        allow_failure: true
      - step: "windows-test"
        allow_failure: true
