# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SETUP_GVM_VERSION: "v0.5.1"

steps:
  - label: ":linux: Testing on {{matrix.platform}}"
    key: linux-test
    command:
      - ".buildkite/scripts/run-go-tests.sh {{matrix.go_version}} {{matrix.platform}}"
    agents:
      provider: "gcp"
      image: "{{matrix.platform}}"
    artifact_paths: "build/*.xml"
    matrix:
      setup:
        go_version:
          - "1.17"
        platform:
          - "family/core-ubuntu-2204"

  - label: ":windows: Testing on Windows"
    key: windows-test
    command: ".buildkite/scripts/run-win-tests.ps1 {{matrix.go_version}}"
    agents:
      provider: "gcp"
      image: "{{matrix.platform}}"
    artifact_paths: "build/*.xml"
    matrix:
      setup:
        go_version:
          - "1.17"
        platform:
          - "family/core-windows-2019"

  - label: ":mac: Testing on MacOS"
    key: macos-test
    command: ".buildkite/scripts/run-go-tests.sh 1.17 generic-13-ventura-x64"
    agents:
      provider: "orka"
      imagePrefix: "generic-13-ventura-x64"
      cpu: 4
    artifact_paths: "build/*.xml"
# Temporarily skipped due to issue with artifact upload
#  - label: ":junit: Junit annotate"
#    plugins:
#      - junit-annotate#v2.4.1:
#          artifacts: "build/*.xml"
#          fail-build-on-error: true
#    agents:
#      provider: "gcp"
#    depends_on:
#      - step: "linux-test"
#        allow_failure: true
#      - step: "windows-test"
#        allow_failure: true
