// Code generated by "stringer -type=Kind -linecomment=true"; DO NOT EDIT.

package vfs

import "strconv"

const _Kind_name = "unknown OS errorpermission deniedfile already existsfile does not existfile already closedno space or quota exhaustedprocess file desciptor limit reachedcannot resolve pathread/write IO erroroperation not supportedfile lock failedfile unlock failedunknown error kind"

var _Kind_index = [...]uint16{0, 16, 33, 52, 71, 90, 117, 153, 172, 191, 214, 230, 248, 266}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
