name: macos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'

    - name: Run test
      uses: magefile/mage-action@v1
        with:
          version: latest
          args: test
